package io.itaiit.mapper;

import io.itaiit.pojo.TbItemCat;

import java.util.List;

public interface TbItemCatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_cat
     *
     * @mbg.generated Tue Nov 19 20:33:25 CST 2019
     */
    int insert(TbItemCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_cat
     *
     * @mbg.generated Tue Nov 19 20:33:25 CST 2019
     */
    List<TbItemCat> selectAll();
}