package io.itaiit.mapper;

import io.itaiit.pojo.TbItemParamItem;

import java.util.List;

public interface TbItemParamItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_param_item
     *
     * @mbg.generated Tue Nov 19 20:33:25 CST 2019
     */
    int insert(TbItemParamItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_param_item
     *
     * @mbg.generated Tue Nov 19 20:33:25 CST 2019
     */
    List<TbItemParamItem> selectAll();
}