package io.itaiit.mapper;

import io.itaiit.pojo.TbItemParam;

import java.util.List;

public interface TbItemParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_param
     *
     * @mbg.generated Tue Nov 19 20:33:25 CST 2019
     */
    int insert(TbItemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_param
     *
     * @mbg.generated Tue Nov 19 20:33:25 CST 2019
     */
    List<TbItemParam> selectAll();
}