package io.itaiit.mapper;

import io.itaiit.pojo.TbOrderShipping;

import java.util.List;

public interface TbOrderShippingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_shipping
     *
     * @mbg.generated Tue Nov 19 20:33:25 CST 2019
     */
    int insert(TbOrderShipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_shipping
     *
     * @mbg.generated Tue Nov 19 20:33:25 CST 2019
     */
    List<TbOrderShipping> selectAll();
}