package io.itaiit.mapper;

import io.itaiit.pojo.TbOrder;

import java.util.List;

public interface TbOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated Tue Nov 19 20:33:25 CST 2019
     */
    int insert(TbOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated Tue Nov 19 20:33:25 CST 2019
     */
    List<TbOrder> selectAll();
}