package io.itaiit.mapper;

import io.itaiit.pojo.TbUser;

import java.util.List;

public interface TbUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Tue Nov 19 20:33:25 CST 2019
     */
    int insert(TbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Tue Nov 19 20:33:25 CST 2019
     */
    List<TbUser> selectAll();
}